import type { Metadata } from "next";
import { Archivo, Geist, Geist_Mono } from "next/font/google";
import { getContent } from "@/lib/content";
import { SITE_URL } from "@/lib/site";
import "./globals.css";

const display = Archivo({
  subsets: ["latin"],
  axes: ["wdth"],
  variable: "--font-display",
  display: "swap",
});
const body = Geist({ subsets: ["latin"], variable: "--font-body", display: "swap" });
const mono = Geist_Mono({ subsets: ["latin"], variable: "--font-mono", display: "swap" });

const content = getContent();

// Derived from content.json rather than written out again here. The previous
// hardcoded copy claimed "Motion Designer" and "motion graphics" — neither of
// which Manish lists as his own work — precisely because it was a second place
// to remember to edit, and nobody did.
const title = `${content.name} — ${content.tagline}`;
const description = content.bio[0];

export const metadata: Metadata = {
  // Required for og:image to resolve to an absolute URL. Without it Next emits
  // a relative path, and every crawler ignores a relative og:image — which is
  // the difference between a link preview with his portrait in it and a grey
  // box with a URL under it.
  metadataBase: new URL(SITE_URL),
  title,
  description,
  alternates: { canonical: "/" },
  // The card itself is generated by app/opengraph-image.tsx; Next picks that
  // file up by convention and fills in og:image, its dimensions and its alt.
  openGraph: {
    type: "profile",
    title,
    description,
    url: "/",
    siteName: content.name,
    locale: "en_US",
  },
  // X/Twitter is not a channel Manish uses, so there is no separate
  // twitter-image: this only upgrades the card from a small thumbnail to the
  // full-width one, and the crawler falls back to og:image for the picture.
  twitter: { card: "summary_large_image", title, description },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${display.variable} ${body.variable} ${mono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
